# Automatically updated by the winget bot at 2021/Aug/25
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: LogMeIn.LastPass
PackageVersion: 4.79.0.2222
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://download.cloud.lastpass.com/windows_installer/LastPassInstaller.msi
  InstallerSha256: 542615EA58296E530A45EB96FF950AFC48B354819CF17BC28CCB6E8765343F72
  ProductCode: "{F913D182-F4F8-480D-988C-3A024178D0A5}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
