# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Tutanota.Tutanota
PackageVersion: 3.87.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://mail.tutanota.com/desktop/tutanota-desktop-win.exe
  InstallerSha256: A611F1F9FC0248C76DAE7B41581600A0508330C9C718229BCE9BA1870FFA530B
  InstallerSwitches:
    Custom: /CURRENTUSER
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://mail.tutanota.com/desktop/tutanota-desktop-win.exe
  InstallerSha256: A611F1F9FC0248C76DAE7B41581600A0508330C9C718229BCE9BA1870FFA530B
  InstallerSwitches:
    Custom: /ALLUSERS
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
