# Automatically updated by the winget bot at 2021/Sep/09
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Google.Drive
PackageVersion: 51.0.9.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Platform:
  - Windows.Desktop
  InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://dl.google.com/drive-file-stream/GoogleDrive.exe
  InstallerSha256: 2ADF5EB9139EF56D2AA73F023398EDDB52BBE6C725DF66DD80CEA8E2650CBA7A
  InstallerSwitches:
    Silent: --silent --gsuite_shortcuts=false
    SilentWithProgress: --silent --gsuite_shortcuts=false
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
