# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Malwarebytes.Malwarebytes
PackageVersion: 4.4.5.130
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://data-cdn.mbamupdates.com/web/mb4-setup-consumer/MBSetup.exe
  InstallerSha256: CED1BD934CE6D6CA4DD712A9D752C32C291C72B32F3B4EAC71934D72D9D8761D
  InstallerSwitches:
    Silent: /VERYSILENT
    SilentWithProgress: /VERYSILENT
    Custom: /SUPPRESSMSGBOXES /NORESTART
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
