# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: KDE.KDEConnect
PackageVersion: 21.08.1.712
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/712/artifact/kdeconnect-kde-21.08.1-712-windows-msvc2019_64-cl.exe
  InstallerSha256: C1A0F5C270D9A2E62A9E7B09832C2C9AFF97D2C97C091D27B9F28E8F5DBFA7B9
  InstallerSwitches:
    Custom: /ALLUSERS
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/712/artifact/kdeconnect-kde-21.08.1-712-windows-msvc2019_64-cl.exe
  InstallerSha256: C1A0F5C270D9A2E62A9E7B09832C2C9AFF97D2C97C091D27B9F28E8F5DBFA7B9
  InstallerSwitches:
    Custom: /CURRENTUSER
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

