# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Postman.Postman
PackageVersion: 8.12.1
MinimumOSVersion: 10.0.0.0
InstallModes:
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://dl.pstmn.io/download/version/8.12.1/win64
  InstallerSha256: 76AEE68DB934C52623BE4AF3406B2820FEB61F888ED2AF241C1ABFCC01FFBE93
  InstallerSwitches:
    Silent: -s
    SilentWithProgress: -s
  UpgradeBehavior: install
  ProductCode: Postman
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://dl.pstmn.io/download/version/8.12.1/win32
  InstallerSha256: C2975335218441E003B2D69ACB3A87B535D5FB44069F9A43A60FCCBCEF00916B
  InstallerSwitches:
    Silent: -s
    SilentWithProgress: -s
  UpgradeBehavior: install
  ProductCode: Postman
ManifestType: installer
ManifestVersion: 1.0.0

