# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Postman.Postman
PackageVersion: 8.12.2
MinimumOSVersion: 10.0.0.0
InstallModes:
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://dl.pstmn.io/download/version/8.12.2/win64
  InstallerSha256: 09E5AF98CA01CD52253E46E7DE474FE4F120EF88433A8CB090878D1E954B2089
  InstallerSwitches:
    Silent: -s
    SilentWithProgress: -s
  UpgradeBehavior: install
  ProductCode: Postman
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://dl.pstmn.io/download/version/8.12.2/win32
  InstallerSha256: C5CF9103C866525882BF2902AF80D827A0CFBBFF47DA49D407F56D6310F0526E
  InstallerSwitches:
    Silent: -s
    SilentWithProgress: -s
  UpgradeBehavior: install
  ProductCode: Postman
ManifestType: installer
ManifestVersion: 1.0.0

