# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: DrakeetXu.PureWriter
PackageVersion: 1.4.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://github.com/PureWriter/desktop/releases/download/1.4.0/PureWriter-1.4.0-Win10-x64.msi
  InstallerSha256: DFC08BC10CEECE7506CCF903BFE7AC9D682C5C1907F32ADB42DC0A7EC2D071B0
  UpgradeBehavior: install
  ProductCode: '{C7F55D76-2067-3969-9D53-99616798D1BF}'
ManifestType: installer
ManifestVersion: 1.0.0
