# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Google.Chrome.Dev
PackageVersion: 95.0.4636.4
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- silent
- silentWithProgress
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/dev/googlechromedevstandaloneenterprise64.msi
  InstallerSha256: D72B0D53EEAC65B435B891D2E1B4AEDB746FBB443C4213E72FA80CFAD9C110FF
  UpgradeBehavior: install
  ProductCode: "{FF32A955-0060-3AB6-B099-A2D0E5602647}"
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/dev/googlechromedevstandaloneenterprise.msi
  InstallerSha256: 549AA9B631CF34B5666F26F9B2FA054B6A3CE135EA3DD68B2D9C2E83389A5203
  UpgradeBehavior: install
  ProductCode: "{C3A0B6F0-CBAE-3527-B352-64EF4EACCFA6}"
ManifestType: installer
ManifestVersion: 1.0.0

