# Automatically updated by the winget bot at 2021/Sep/04
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json
PackageIdentifier: xiaomi.miuiplus
PackageVersion: 2.3.2.1028
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0
