# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Spotify.Spotify
PackageVersion: 1.1.67.586.gbb5ef64e
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://download.scdn.co/SpotifyFullSetup.exe
  InstallerSha256: 6B6A2B392D43B762D18205FD69D67025F0F1960A0CEBB83278E15D1E49C6D6C4
  InstallerSwitches:
    Silent: /Silent
    SilentWithProgress: /Silent
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

