# Automatically updated by the winget bot at 2021/Sep/04
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Wondershare.DemoCreator
PackageVersion: 5.1.2.18
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://download.wondershare.com/cbs_down/democreator_full7743.exe
  InstallerSha256: 67C779EB8A5F41E0A48E0D919005332339A10F9EA7463A9E2BBF25FE71DD7B25
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
