# Created using wingetcreate 0.3.0.6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json

PackageIdentifier: SmartSoft.SmartFTP
PackageVersion: 10.0.2913.0
PackageLocale: en-US
Publisher: SmartSoft Ltd.
PublisherUrl: https://www.smartftp.com
PublisherSupportUrl: https://www.smartftp.com/support
Author: SmartSoft Ltd.
PackageName: SmartFTP Client
License: Commercial
LicenseUrl: https://www.smartftp.com/static/Products/Client/License.txt
ShortDescription: SmartFTP is a fast and reliable FTP, FTPS, SFTP, HTTP, Amazon S3, WebDAV, Google Drive, Google Cloud Storage, Microsoft OneDrive, Backblaze B2, Telnet, Terminal client with lots of features and a modern user interface.
Moniker: smartftp
Tags:
- ftp
- sftp
- webdav
- onedrive
- gdrive
- ssh
MinimumOSVersion: 10.0.14393.0
Installers:
- InstallerLocale: en-US
  Platform:
  - Windows.Desktop
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://static.smartftp.com/static/Products/Client/10.0.2913.0/x64/SmartFTP.msi
  InstallerSha256: BD6E976E458459870CD63F24B9433BF1407A20E21E29A741518D450EFDF19D7D
  ProductCode: '{63E7610A-AAB6-4C81-AA61-F33E08A939A3}'
ManifestType: singleton
ManifestVersion: 1.0.0

