# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Google.Chrome.Beta
PackageVersion: 93.0.4577.51
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- silent
- silentWithProgress
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  InstallerSha256: 054B8196FA9A718E9623BEE28C2A37DC31F1CBE8FB6F4C875572C5231544ECBA
  UpgradeBehavior: install
  ProductCode: "{32044F2A-CE2E-3941-9748-099008672E64}"
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
  InstallerSha256: 28894E47F5032631750CAE6E4ABE937FB0081B85E418F2B008A6030DF9E6D123
  UpgradeBehavior: install
  ProductCode: "{658D0DB0-76F1-3E06-A611-72291DAABC8E}"
ManifestType: installer
ManifestVersion: 1.0.0

