# Created using YamlCreate.ps1 v1.1.6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: EuSoft.Eudic
PackageVersion: 12.0.0.0
MinimumOSVersion: 10.0.0.0
FileExtensions:
- mdx
- ld2
- bgl
- eudic
InstallModes:
- interactive
- silentWithProgress
Installers:
- InstallerLocale: zh-CN
  Architecture: x86
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://static.frdic.com/pkg/eudic_win.exe?v=2021-08-19
  InstallerSha256: 9B3AD96D5A4B5AEF051671D8CA13E13820902AEDDE86690E7A51E760AA038E9B
  InstallerSwitches:
    Silent: /SD
    SilentWithProgress: /SD
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

