# Automatically updated by the winget bot at 2021/Aug/28
# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: Belarc.Advisor
PackageVersion: 9.7.0.0
PackageName: Belarc Advisor
Publisher: Belarc Inc.
License: Copyright (c) Belarc Inc.
Moniker: advisor
Tags:
- advisor
- belarc
- benchmark
- info
- profile
- profiling
ShortDescription: The Belarc Advisor builds a detailed profile of your installed software and hardware, network inventory, any missing Microsoft hotfixes, anti-virus status, security benchmarks, and displays the results in your Web browser.
Installers:
- Architecture: x86
  InstallerUrl: https://downloads.belarc.com/advisor/advisorinstaller.exe
  InstallerSha256: FD6104BC6B2106660C1B1D2939E907DF4D2D85509C5760D4BFCDFF71AE7684DE
  InstallerType: exe
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
