# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: Microsoft.VisualStudio.2019.Enterprise
PackageVersion: 16.11.2
PackageName: Visual Studio Enterprise 2019
Publisher: Microsoft
License: Copyright (c) Microsoft Corporation
LicenseUrl: https://visualstudio.microsoft.com/license-terms/
Moniker: vs2019-enterprise
Tags:
- C++
- vs
- C#
ShortDescription: Visual Studio Enterprise
PackageUrl: https://visualstudio.microsoft.com/
Installers:
- Architecture: x64
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/bacf7555-1a20-4bf4-ae4d-1003bbc25da8/63903b981fb67df5b24aacd4d8383b2593bb4c192ece3d07d19452640e7588d9/vs_Enterprise.exe
  InstallerSha256: 63903B981FB67DF5B24AACD4D8383B2593BB4C192ECE3D07D19452640E7588D9
  InstallerType: exe
  InstallerSwitches:
    Silent: --quiet
    SilentWithProgress: --passive
    Custom: --productId Microsoft.VisualStudio.Product.Enterprise --channelId VisualStudio.16.Release --channelUri https://aka.ms/vs/16/release/channel --add Microsoft.VisualStudio.Workload.Universal
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

