# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: Microsoft.VisualStudio.2019.Professional
PackageVersion: 16.11.2
PackageName: Visual Studio Professional 2019
Publisher: Microsoft Corporation
PackageUrl: https://visualstudio.microsoft.com/
License: Copyright (c) Microsoft Corporation. All rights reserved.
LicenseUrl: https://visualstudio.microsoft.com/license-terms/
Moniker: vs2019-professional
Tags:
- C++
- vs
- C#
Commands:
- devenv
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/bacf7555-1a20-4bf4-ae4d-1003bbc25da8/8ec4a2d3e71b056c6165792bf3b3c6155b7a84103f64754b62275adaaa99467a/vs_Professional.exe
  InstallerSha256: 8EC4A2D3E71B056C6165792BF3B3C6155B7A84103F64754B62275ADAAA99467A
  InstallerSwitches:
    Silent: --quiet
    SilentWithProgress: --passive
    Custom: --productId Microsoft.VisualStudio.Product.Professional --channelId VisualStudio.16.Release --channelUri https://aka.ms/vs/16/release/channel --add Microsoft.VisualStudio.Workload.Universal
ShortDescription: Microsoft.VisualStudio.Professional
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

