# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Google.Chrome
PackageVersion: 93.0.4577.63
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise64.msi
  InstallerSha256: A1F5DE9B726DB664A5F15DD0A777F75C5F8C240F176CACF696B9C74ED2407A60
  UpgradeBehavior: install
  ProductCode: "{32490FC2-5E1B-3CB2-9D0C-3FA41E9439E9}"
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi
  InstallerSha256: 148D77180C613FD44F2CEE39A6283B4E437D89D290E2B4914A482E64A2808A07
  UpgradeBehavior: install
  ProductCode: "{4B0E6BED-689D-3D0C-A3D7-ED36C01FEB19}"
ManifestType: installer
ManifestVersion: 1.0.0

