# Automatically updated by the winget bot at 2021/Aug/31
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Wondershare.Filmora
PackageVersion: 10.5.9.10
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://download.wondershare.com/cbs_down/filmora_64bit_full846.exe
  InstallerSha256: AEC479254CA2EB041FFE9010FDA3579303AB8D8E130BF3502F25069550D94937
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
