# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: Microsoft.VisualStudio.2019.BuildTools
PackageVersion: 16.11.2
PackageName: Visual Studio Build Tools 2019
Publisher: Microsoft
License: Copyright (c) Microsoft Corporation. All rights reserved.
LicenseUrl: https://visualstudio.microsoft.com/license-terms/
Tags:
- C++
- tools
- C#
- build
- vs
ShortDescription: Visual Studio Build Tools
PackageUrl: https://visualstudio.microsoft.com/
Installers:
- Architecture: x64
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/bacf7555-1a20-4bf4-ae4d-1003bbc25da8/f3a7e2868c203490a4095231e20e628bf661b7469f2d53626f3fbbdfc161d471/vs_BuildTools.exe
  InstallerSha256: F3A7E2868C203490A4095231E20E628BF661B7469F2D53626F3FBBDFC161D471
  InstallerType: exe
  InstallerSwitches:
    Silent: --quiet
    SilentWithProgress: --passive
    Custom: --productId Microsoft.VisualStudio.Product.BuildTools --channelId VisualStudio.16.Release --channelUri https://aka.ms/vs/16/release/channel
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
Moniker: vs2019-buildtools

