# Created using wingetcreate 0.3.0.6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: Google.ChromeRemoteDesktop
PackageVersion: 92.0.4515.41
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0

