# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Google.Chrome
PackageVersion: "10"
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi
  InstallerSha256: 60EC70E7BF0F6859338554EB42B1465921CE0BCE723449AA6BC67079DE27A6E5
- Architecture: x86
  InstallerUrl: https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi
  InstallerSha256: 60EC70E7BF0F6859338554EB42B1465921CE0BCE723449AA6BC67079DE27A6E5
ManifestType: installer
ManifestVersion: 1.0.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
ProductCode: ttps://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi
