# Automatically updated by the winget bot at 2021/Sep/09
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Nord.NordLocker
PackageVersion: 2.2.12.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
    MinimumVersion: 14.28.29913.0
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://downloads.nordcdn.com/apps/windows/NordLocker/NordLockerSetup.exe
  InstallerSha256: A85697E8C6730E939092D92367AA8E63D78D3B99FD3253224B70213CCB4475A2
  InstallerSwitches:
    Silent: /SILENT
    SilentWithProgress: /SILENT
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
