# Automatically updated by the winget bot at 2021/Sep/09
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Kakao.KakaoTalk
PackageVersion: 3.3.3.2911
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Installers:
- InstallerLocale: ko-KR
  Architecture: x86
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://app-pc.kakaocdn.net/talk/win32/KakaoTalk_Setup.exe
  InstallerSha256: C6FC72800AB25DEFD88DDDF1B2D3188C269C0903BF7B003CC13B9319257D9D8D
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
