# Created with YamlCreate.ps1 v2.1.5 $debug=AUSU.CRLF.5-1-19041-1682.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Google.Chrome
PackageVersion: 1.0.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
  InstallerSha256: 0BED2D6FC54B3696C360E97F940E3C5F4700C809A6D4DD2C454361393D0594F1
  ProductCode: '{F3C37EDB-F5E6-3496-A8DA-EA44246E32D1}'
- Architecture: x86
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise.msi
  InstallerSha256: EF9064C8E0A78618B5C2350FC07D34A2A81175EAB73C63CA7765459B6F89DE78
  ProductCode: '{0E8830BB-B5B2-3452-894A-095E38262C6D}'
ManifestType: installer
ManifestVersion: 1.2.0
