# Automatically updated by the winget bot at 2021/Aug/19
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Nord.NordLocker
PackageVersion: 2.2.11.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
    MinimumVersion: 14.28.29913.0
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://downloads.nordcdn.com/apps/windows/NordLocker/NordLockerSetup.exe
  InstallerSha256: CEAA6D25E527E897EF05CB5DB8DDAC64AEEB10B3016DAFFE11613F5B3EA08E50
  InstallerSwitches:
    Silent: /SILENT
    SilentWithProgress: /SILENT
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
