# Automatically updated by the winget bot at 2021/Sep/07
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: SoftPerfect.SoftPerfectNetworkScanner
PackageVersion: 8.1.1
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
FileExtensions:
- xml
- txt
- html
- htm
- csv
- json
- db
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://www.softperfect.com/download/files/netscan_setup.exe
  InstallerSha256: EE051ABDE94811DF29899B5FEE04544AB7E233A1E92EB981300317290FA84AFF
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
