# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Miro.Miro
PackageVersion: 0.5.6
MinimumOSVersion: 10.0.0.0
InstallModes:
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://desktop.miro.com/platforms/win32/Miro.exe
  InstallerSha256: 57528459F3D0DBCF4B36A1F4C492C3278E397E8BB523004799453DC98C0128B6
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://desktop.miro.com/platforms/win32-x86/Miro.exe
  InstallerSha256: 26CD65BDA43044704CE787BBC9A1CBF5B6127ACA2F6E245D7AA8E28DE68DA969
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
