# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Wondershare.Filmora
PackageVersion: 10.5.7.4
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://download.wondershare.com/cbs_down/filmora_64bit_full846.exe
  InstallerSha256: AB68256DC19B98B20C0B5B73AC3EEDCEB6528B824F6D732D87B2E9F2AC8A8522
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
