# Automatically updated by the winget bot at 2021/Aug/19
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: KakaoEnterprise.KakaoWork
PackageVersion: 1.8.1.2429
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Platform:
  - Windows.Desktop
  InstallerLocale: ko-KR
  Architecture: x86
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://t1.kakaocdn.net/kakaowork/win/prod/release/KakaoWork_Setup.exe
  InstallerSha256: CD76C7F3FC1164A98AB0F718D7C81CE12F8859F27BF72BFFE2608174163ECF9C
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
