# Created using wingetcreate 0.3.0.6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Mozilla.Firefox.Nightly
PackageVersion: 93.0a1
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
- pdf
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central/firefox-93.0a1.en-US.win64.installer.exe
  InstallerSha256: D49E99E76ED86A4550C0C36A8F403A9212BB205E3F87632516A414FDADCDA3D1
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
  UpgradeBehavior: install
  ProductCode: Nightly 93.0a1 (x64 en-US)
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central/firefox-93.0a1.en-US.win32.installer.exe
  InstallerSha256: 95CA9380BA2C0FA3ED5DD1A51CC4E96ED6FC57342A3085E2C5CB25035A81C2E0
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
  UpgradeBehavior: install
  ProductCode: Nightly 93.0a1 (x86 en-US)
- InstallerLocale: en-US
  Architecture: arm64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central/firefox-93.0a1.en-US.win64-aarch64.installer.exe
  InstallerSha256: 2065495E9EC85A1C3B7F7820C5A936AE6C1F952C074908287973CB5DFDCAE57B
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

