# Created using YamlCreate.ps1 v1.1.6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.0.0.schema.json

PackageIdentifier: alibaba.dingtalk
PackageVersion: 6.0.22-Release.7190187
PackageLocale: en-US
Publisher: Alibaba (China) Network Technology Co.,Ltd.
PublisherUrl: https://www.alibabagroup.com/en/global/home
PublisherSupportUrl: https://survey.aliyun.com/apps/zhiliao/LWuswjFCS
PrivacyUrl: https://terms.alicdn.com/legal-agreement/terms/suit_bu1_dingtalk/suit_bu1_dingtalk202102181006_34132.html
#Author: 
PackageName: DingTalk
PackageUrl: https://www.dingtalk.com/en/
License: Freeware
LicenseUrl: https://page.dingtalk.com/wow/dingtalk/act/service-en-lite
Copyright: Copyright Notice © 1999-2021 Alibaba Group Holding Limited and/or its affiliates and licensors. All rights reserved.
CopyrightUrl: https://page.dingtalk.com/wow/dingtalk/act/service-en-lite
ShortDescription: Dingtalk, make work and study easy
Description: DingTalk is an intelligent working platform created by Alibaba Group to support tens of millions of enterprises to achieve higher working efficiency with the new digitalized working method.
# Moniker: dingding
Tags:
- dingding
- dingtalk
ManifestType: locale
ManifestVersion: 1.0.0

