# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: ElijahLopez.MusicCaster
PackageVersion: 4.90.90
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Protocols:
- https
- http
Installers:
- Architecture: x86
  InstallerType: inno
  Scope: user
  InstallerUrl: https://github.com/elibroftw/music-caster/releases/download/v4.90.90/Music.Caster.Setup.exe
  InstallerSha256: C19EC2F1149E5C19D7CA0461A60A1E4FF7153546937E524920FD3A31C12B5001
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
