# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: KDE.KDEConnect
PackageVersion: 21.08.0.687
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/687/artifact/kdeconnect-kde-21.08.0-687-windows-msvc2019_64-cl.exe
  InstallerSha256: D9C68EFBC799E78BA31DD5BC13595A6C9710EEB9A55C984392E9D17348C7BB26
  InstallerSwitches:
    Custom: /ALLUSERS
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/687/artifact/kdeconnect-kde-21.08.0-687-windows-msvc2019_64-cl.exe
  InstallerSha256: D9C68EFBC799E78BA31DD5BC13595A6C9710EEB9A55C984392E9D17348C7BB26
  InstallerSwitches:
    Custom: /CURRENTUSER
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

