# Automatically updated by the winget bot at 2021/Sep/01
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: ElectronicArts.EADesktop
PackageVersion: 12.0.124.4989
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2010Redist-x86
    MinimumVersion: 10.0.40219
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
    MinimumVersion: 14.28.29325.2
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x86
    MinimumVersion: 14.28.29325.2
Installers:
- Platform:
  - Windows.Desktop
  Architecture: x64
  InstallerType: burn
  Scope: machine
  InstallerUrl: https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EADesktopInstaller.exe
  InstallerSha256: 4D6262691E1F17D8C27AAAE69E78586D0635B1E194CCAAB17D8DF47D84CB272F
  UpgradeBehavior: install
  ProductCode: '{C2622085-ABD2-49E5-8AB9-D3D6A642C091}'
ManifestType: installer
ManifestVersion: 1.0.0
