# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: baidu.baidu-devtool
PackageVersion: 3.37.1
FileExtensions:
- js
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://b.bdstatic.com/miniapp/development_tool/fbf41/%E7%99%BE%E5%BA%A6%E5%BC%80%E5%8F%91%E8%80%85%E5%B7%A5%E5%85%B7-3.37.1-x64.exe
  InstallerSha256: 5D11373C0153546CD7455A7830BF62D9FDEA43FD9CD41D8F79470EBA54ED8B12
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://b.bdstatic.com/miniapp/development_tool/fbf41/%E7%99%BE%E5%BA%A6%E5%BC%80%E5%8F%91%E8%80%85%E5%B7%A5%E5%85%B7-3.37.1-x64.exe
  InstallerSha256: 5D11373C0153546CD7455A7830BF62D9FDEA43FD9CD41D8F79470EBA54ED8B12
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.0.0


