# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Tableau.Desktop
PackageVersion: 21.3.814
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2013Redist-x64
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: burn
  Scope: machine
  InstallerUrl: https://downloads.tableau.com/tssoftware/TableauDesktop-64bit-2021-3-0.exe
  InstallerSha256: 4038CE5552CEBB0DA50122C867374BFB40EFE6DE429078487D83365EF076FF87
  InstallerSwitches:
    Custom: ACCEPTEULA=1
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

