# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: TopalaSoftwareSolutions.SIW
PackageVersion: 2021.08.24a
Platform:
- Windows.Desktop
MinimumOSVersion: 6.1.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://siw64.com/download/siwtrial-setup.exe
  InstallerSha256: 7CE7127793BDCB89BD391B585C377060134C1E25B27FC312BA3D7AB04ED2700F
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
