# Created using wingetcreate 0.3.0.6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Mozilla.Firefox.Nightly
PackageVersion: 94.0a1
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
- pdf
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central/firefox-94.0a1.en-US.win64.installer.exe
  InstallerSha256: 73193261647bd91bea5d8af870965bb624022f5e267de6afd941faa703fbb776
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central/firefox-94.0a1.en-US.win32.installer.exe
  InstallerSha256: F7C6864DFA5E23425C86FAF714174C770C3F9DAD94F00C8F24849827BC52B93C
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: arm64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central/firefox-94.0a1.en-US.win64-aarch64.installer.exe
  InstallerSha256: 137595BD411CCA7290E131FCFB87E999718AE919DE482573062DA518954760EB
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

