# Created with YamlCreate.ps1 v2.4.3 $debug=AUSU.CRLF.7-4-6.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: wangyu.BilibiliVideoDownload
PackageVersion: 3.0.6
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/blogwy/BilibiliVideoDownload/releases/download/v3.0.6/BilibiliVideoDownload.Setup.3.0.6.exe
  InstallerSha256: 6A6FC3F582CB9EF5A4B3663DB199B74C7515186B89665EE04C1789306DD1F96D
ManifestType: installer
ManifestVersion: 1.9.0
