# Created using wingetcreate 0.3.0.6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: CPUID.CPU-Z
PackageVersion: 1.97
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://download.cpuid.com/cpu-z/cpu-z_1.97-en.exe
  InstallerSha256: 825A5E768DF385AD651B16256755A63D91FB710E46296D3B0D05E9DF7EEEDAFF
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

