# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Malwarebytes.Privacy
PackageVersion: 3.4.0.661
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /NORESTART
  Silent: /VERYSILENT
  SilentWithProgress: /VERYSILENT
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://data-cdn.mbamupdates.com/web/mbprivacy/win/online/MBPrivacySetup.exe
  InstallerSha256: 7B2A03580F87A1CD9F6AB3955D643B2CB1C8A872758D6F7F47C95D86104670ED
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
