PackageIdentifier: LutzRoeder.Netron
PackageVersion: 5.2.1
Platform:
- Windows.Desktop
InstallModes:
- silent
- silentWithProgress
Installers:
- Architecture: x86
  Scope: user
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v5.2.1/Netron-Setup-5.2.1.exe
  InstallerSha256: E0A8276173148B17CC96951EA3C26AAF39C536B2796B0A027C010D522AA8CEAC
  InstallerLocale: en-US
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
- Architecture: arm64
  Scope: user
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v5.2.1/Netron-Setup-5.2.1.exe
  InstallerSha256: E0A8276173148B17CC96951EA3C26AAF39C536B2796B0A027C010D522AA8CEAC
  InstallerLocale: en-US
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
FileExtensions:
- armnn
- caffemodel
- cmf
- dnn
- h5
- hd5
- hdf5
- keras
- lite
- mar
- meta
- mlmodel
- mlpackage
- mnn
- model
- nn
- om
- onnx
- paddle
- param
- pb
- pbtxt
- pdmodel
- pdparams
- prototxt
- pt
- pth
- rknn
- t7
- tfl
- tflite
- tmfile
- uff
- xmodel
ManifestType: installer
ManifestVersion: 1.0.0
