# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: plex.Plex
PackageVersion: 1.34.1
MinimumOSVersion: 10.0.0.0
Platform:
- Windows.Desktop
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSuccessCodes:
- 1223
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
    MinimumVersion: 14.28.29913.0
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://downloads.plex.tv/plex-desktop/1.34.1.2590-74ea7099/windows/Plex-1.34.1.2590-74ea7099-x86_64.exe
  InstallerSha256: A0009490A523F852AEF57CE150CC3D59E8A6740772DEECCCF02D6D10A2FDD116
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

